# Generated by Django 6.0.3 on 2026-03-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
